-- tests/core/intent_spec.lua
describe("intent", function()
  local intent = require("novim.core.intent")

  describe("classify", function()
    it("returns 'explain' for explanation questions", function()
      assert.equals("explain", intent.classify("what does this function do"))
      assert.equals("explain", intent.classify("why is this variable here"))
      assert.equals("explain", intent.classify("how does this work"))
      assert.equals("explain", intent.classify("explain this code"))
      assert.equals("explain", intent.classify("describe what happens here"))
      assert.equals("explain", intent.classify("tell me about this"))
      assert.equals("explain", intent.classify("walk me through this"))
    end)

    it("returns 'diagnose' for error/problem questions", function()
      assert.equals("diagnose", intent.classify("why is this erroring"))
      assert.equals("diagnose", intent.classify("what's wrong with this"))
      assert.equals("diagnose", intent.classify("this is broken"))
      assert.equals("diagnose", intent.classify("there's a bug here"))
      assert.equals("diagnose", intent.classify("I have an issue"))
      assert.equals("diagnose", intent.classify("this doesn't work"))
      assert.equals("diagnose", intent.classify("not working at all"))
    end)

    it("returns 'fix' for fix requests", function()
      assert.equals("fix", intent.classify("fix this"))
      assert.equals("fix", intent.classify("fix it"))
      assert.equals("fix", intent.classify("repair this function"))
      assert.equals("fix", intent.classify("solve this problem"))
      assert.equals("fix", intent.classify("resolve this error"))
      assert.equals("fix", intent.classify("correct the typo"))
    end)

    it("returns 'refactor' for refactoring requests", function()
      assert.equals("refactor", intent.classify("refactor this function"))
      assert.equals("refactor", intent.classify("clean up this code"))
      assert.equals("refactor", intent.classify("simplify this"))
      assert.equals("refactor", intent.classify("improve this logic"))
      assert.equals("refactor", intent.classify("optimize this loop"))
    end)

    it("returns 'write' for creation requests", function()
      assert.equals("write", intent.classify("write a function that sorts"))
      assert.equals("write", intent.classify("create a new class"))
      assert.equals("write", intent.classify("add error handling"))
      assert.equals("write", intent.classify("implement a cache"))
      assert.equals("write", intent.classify("generate a test"))
      assert.equals("write", intent.classify("build a parser"))
    end)

    it("returns 'explain' as default for ambiguous input", function()
      assert.equals("explain", intent.classify("hmm"))
      assert.equals("explain", intent.classify("ok"))
      assert.equals("explain", intent.classify(""))
    end)

    it("is case insensitive", function()
      assert.equals("fix", intent.classify("FIX THIS"))
      assert.equals("explain", intent.classify("WHAT does this do"))
      assert.equals("refactor", intent.classify("REFACTOR please"))
    end)

    it("prioritizes fix over diagnose when both match", function()
      assert.equals("fix", intent.classify("fix this error"))
    end)

    it("prioritizes diagnose over explain for error-like questions", function()
      assert.equals("diagnose", intent.classify("what is wrong here"))
    end)

    it("handles nil input gracefully", function()
      assert.equals("explain", intent.classify(nil))
    end)

    it("prioritizes fix over write when both match", function()
      assert.equals("fix", intent.classify("fix and add a test"))
    end)

    it("prioritizes write over diagnose for creation with error words", function()
      assert.equals("write", intent.classify("add error handling"))
      assert.equals("write", intent.classify("create a bug tracker"))
    end)

    it("handles multi-line input", function()
      assert.equals("fix", intent.classify("can you please\nfix this function"))
    end)

    it("handles input with only whitespace", function()
      assert.equals("explain", intent.classify("   "))
    end)

    it("matches patterns at different positions in text", function()
      assert.equals("explain", intent.classify("I don't understand what this does"))
      assert.equals("fix", intent.classify("please fix the login handler"))
      assert.equals("refactor", intent.classify("can you refactor the database module"))
    end)
  end)
end)
